context = "koch-kube"

[metadata]
    org = "github.com/koch/"
    maintainer = "Alexander Koch"
    description = "Deployments for personal cluster"

[namespaces]
    [namespaces.infrastructure]
    [namespaces.core]
    [namespaces.cert-manager]
    [namespaces.development-infrastructure]

[helmRepos]
    jetstack = "https://charts.jetstack.io/"
    ingress-nginx = "https://kubernetes.github.io/ingress-nginx"
    hashicorp = "https://helm.releases.hashicorp.com"
    teleport = "https://charts.releases.teleport.dev"
    concourse = "https://concourse-charts.storage.googleapis.com/"
    prometheus-community = "https://prometheus-community.github.io/helm-charts"
    grafana = "https://grafana.github.io/helm-charts"

[apps]
    [apps.ingress]
        namespace = "infrastructure"
        enabled = true
        chart = "ingress-nginx/ingress-nginx"
        version = "3.12.0"
    [apps.cert-manager]
        namespace = "cert-manager"
        enabled = true
        chart = "jetstack/cert-manager"
        version = "1.1.0"
        valuesfile = "valuefiles/cert-manager/values.yaml"
    [apps.consul]
        namespace = "core"
        enabled = true
        chart = "hashicorp/consul"
        version = "0.25.0"
        valuesfile = "valuefiles/consul/values.yaml"
    [apps.teleport]
        namespace = "core"
        enabled = true
        chart = "teleport/teleport"
        version = "0.0.7"
        valuesfile = "valuefiles/teleport/values.yaml"
    [apps.concourse]
        namespace = "development-infrastructure"
        enabled = true
        chart = "concourse/concourse"
        version = "14.4.0"
        valuesfile = "valuefiles/concourse/values.yaml"
    [apps.prometheus]
        namespace = "core"
        enabled = true
        chart = "prometheus-community/prometheus"
        version = "12.0.1"
        valuesfile = "valuefiles/prometheus/values.yaml"
    [apps.grafana]
        namespace = "core"
        enabled = true
        chart = "grafana/grafana"
        version = "6.1.10"
        valuesfile = "valuefiles/grafana/values.yaml"
