context = "koch-kube"

[metadata]
    org = "github.com/koch/"
    maintainer = "Alexander Koch"
    description = "Deployments for personal cluster"

[namespaces]
    [namespaces.gitea]
    [namespaces.infrastructure]

[helmRepos]
    gitea-charts = "https://dl.gitea.io/charts/"
    jetstack = "https://charts.jetstack.io/"
    ingress-nginx = "https://kubernetes.github.io/ingress-nginx"

[apps]
    [apps.ingress]
        namespace = "infrastructure"
        enabled = true
        chart = "ingress-nginx/ingress-nginx"
        version = "3.12.0"
    [apps.cert-manager]
        namespace = "infrastructure"
        enabled = true
        chart = "jetstack/cert-manager"
        version = "1.1.0"
        [apps.cert-manager.set]
            "installCRDs" = "true"
    [apps.gitea]
        namespace = "gitea"
        enabled = true
        chart = "gitea-charts/gitea"
        version = "2.0.7"
        [apps.gitea.set]
            "gitea.config.APP_NAME" = "Gitea"
