context = "koch-kube"

[metadata]
    org = "github.com/koch/"
    maintainer = "Alexander Koch"
    description = "Deployments for personal cluster"

[namespaces]
    [namespaces.infrastructure]
    [namespaces.core]
    [namespaces.cert-manager]
    [namespaces.development-infrastructure]

[helmRepos]
    jetstack = "https://charts.jetstack.io/"
    ingress-nginx = "https://kubernetes.github.io/ingress-nginx"
    hashicorp = "https://helm.releases.hashicorp.com"

[apps]
    [apps.ingress]
        namespace = "infrastructure"
        enabled = true
        chart = "ingress-nginx/ingress-nginx"
        version = "3.12.0"
    [apps.cert-manager]
        namespace = "cert-manager"
        enabled = true
        chart = "jetstack/cert-manager"
        version = "1.1.0"
        valuesfile = "valuefiles/cert-manager/values.yaml"
    [apps.consul]
        namespace = "core"
        enabled = true
        chart = "hashicorp/consul"
        version = "0.25.0"
        valuesfile = "valuefiles/consul/values.yaml"
