context = "koch-kube"

[metadata]
    org = "github.com/koch/"
    maintainer = "Alexander Koch"
    description = "Deployments for personal cluster"

[namespaces]
    [namespaces.infrastructure]
    [namespaces.core]
    [namespaces.cert-manager]
    [namespaces.development-infrastructure]

[helmRepos]
    jetstack = "https://charts.jetstack.io/"
    ingress-nginx = "https://kubernetes.github.io/ingress-nginx"
    hashicorp = "https://helm.releases.hashicorp.com"
    teleport = "https://charts.releases.teleport.dev"
    center = "https://repo.chartcenter.io"

[apps]
    [apps.ingress]
        namespace = "infrastructure"
        enabled = true
        chart = "ingress-nginx/ingress-nginx"
        version = "3.12.0"
    [apps.cert-manager]
        namespace = "cert-manager"
        enabled = true
        chart = "jetstack/cert-manager"
        version = "1.1.0"
        [apps.cert-manager.set]
            "installCRDs" = "true"
    [apps.consul]
        namespace = "core"
        enabled = true
        chart = "hashicorp/consul"
        version = "0.25.0"
        [apps.consul.set]
            "global.name" = "consul"
            "connectInject.enabled" = "true"
    [apps.teleport]
        namespace = "core"
        enabled = true
        chart = "teleport/teleport"
        version = "0.0.7"
        valuesfile = "valuefiles/teleport/values.yaml"
        [apps.teleport.set]
            "license.enabled" = "false"
            "config.public_address" = "teleport.akoch.net"
    [apps.artifactory]
        namespace = "development-infrastructure"
        enabled = true
        chart = "center/jfrog/artifactory-oss"
        version = "3.3.0"
        valuesfile = "valuefiles/artifactory/values.yaml"
