ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    cert-manager.io/clusterissuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
  hosts:
    nexus.akoch.net:
    - /
  tls:
   - secretName: teleport-ingress-tls
     hosts:
     - nexus.akoch.net
persistence:
  storageSize: 50Gi
