apiVersion: certmanager.io/v1
kind: ClusterIssuer
metadata:
  name: buypass-prod
  namespace: infrastructure
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    email: ssl@akoch.org
    privateKeySecretRef:
      name: buypass-prod
    http01: {}
