apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: buypass-prod
spec:
  acme:
    server: https://api.buypass.com/acme/directory
    email: ssl@akoch.org
    privateKeySecretRef:
      name: buypass-prod
    http01: {}
