persistence:
  enabled: true

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/issuer: "letsencrypt-prod"
  hosts:
    - grafana.akoch.net
  tls:
   - secretName: grafana-ingress-tls
     hosts:
     - grafana.akoch.net
