# This is a basic workflow to help you get started with Actions

name: Deploy

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: cluster-1
  GKE_ZONE: europe-north1

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - uses: azure/setup-kubectl@v1
        id: install-kubectl

      - uses: azure/setup-helm@v1
        id: install-helm

      - name: Install the helm-diff plugin
        run: helm plugin install https://github.com/databus23/helm-diff

      - name: Create binary location
        run: mkdir -p ~/bin

      - name: Install Helmsman
        run: curl -L https://github.com/Praqma/helmsman/releases/download/v3.6.2/helmsman_3.6.2_linux_amd64.tar.gz | tar zx

      - name: Move Helmsman
        run: mv helmsman ~/bin/helmsman

      - run: |-
        gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

      - name: Run Helmsman
        run: ~/bin/helmsman --apply -f config.toml

      - name: Add cluster issuers
        run: kubectl apply -f other/cert-issuer
